### PR TITLE
Updating mix cloud elements and servers

### PR DESCRIPTION
**Pull request by voidet**
Looks like originals server was not found.
Updated paging mechanism that follows paging html entities.
Updated check of preview string length to properly retrieve server address and full path
Also skipping episodes that have been disabled due to licensing.

### CODE REVIEW

**Comment by voidet** [comment]
As a note it appears that mixcloud have user agent checks in place. I was unable to get these streams loaded via iTunes. I could however get working downloads via Overcast. So if the downloads fail to load then try a different client. Not perfect, but not paying for a proxy server :D

**Comment by mthornto88** [comment]
Thanks Viodet!! It's loading now. But all the dates are showing up as 12/31/69. Any way to fix that?

**Comment by mthornto88** [comment]
And what is strange is that the feed shows the correct date, but Itunes doesn't reflect that.

**Comment by voidet** [comment]
@mthornto88 probably coming back in a format iTunes doesn't like. I saw that iTunes was getting blocked from downloading the items also. So mixcloud probably has a user agent check. Overcast on iOS works fine. I can open a separate PR to fix dates soon

**Comment by voidet** [comment]
Dates fixed in this PR also @mthornto88 
Also I've tweaked the script a bit to better fit cron tasks with multiple feeds:
https://gist.github.com/voidet/1e0333c573c3277e1dee

**Pull request merged**
